# Generated by Django 5.2 on 2025-09-01 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(null=True)),
                ('telegram_verification_token', models.CharField(max_length=64, null=True, unique=True)),
                ('telegram_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250)),
                ('meaning', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabs', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.vocabulary')),
            ],
        ),
        migrations.CreateModel(
            name='UserVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared_count', models.IntegerField(default=0)),
                ('knew_count', models.IntegerField(default=0)),
                ('didnt_know_count', models.IntegerField(default=0)),
                ('last_appeared', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval', models.IntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_progress', to='core.userprofile')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='core.vocabulary')),
            ],
            options={
                'unique_together': {('user', 'vocabulary')},
            },
        ),
    ]
