# Generated by Django 5.2 on 2025-09-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vocabularyimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyimage',
            name='flag',
            field=models.BooleanField(default=0),
        ),
    ]
