# Generated by Django 5.2 on 2025-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_vocabularyimage_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyimage',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
